### ISSUE TITLE
Hostmster is not starting

### ISSUE THREAD

**Issue by Yusadolat** [aegir-project/dockerfiles#23]
After running docker-compose up I got the following error

ERROR: for hostmaster  Cannot start service hostmaster: failed to create endpoint aegirdockerfile_hostmaster_1 on network aegirdockerfile_default: Error starting userland proxy: listen tcp 0.0.0.0:80: listen: address already in use
ERROR: Encountered errors while bringing up the project.

**Comment by helmo** [comment]
Then something else is running on port 80 already... another container? or a webserver on your host OS?

**Comment by Yusadolat** [comment]
Thanks @helmo It true.
I actually solved this by changing the port to 81.
