### ISSUE TITLE
Hostmaster Login Link 404 not found

### ISSUE THREAD

**Issue by Yusadolat** [aegir-project/dockerfiles#24]
After the port issue was resolved and the installation has completed the login link that was given to is not valid

here is the look.

hostmaster_1  | You should now log in to the Aegir frontend by opening the following link in your web browser:
hostmaster_1  | 
hostmaster_1  | http://local.computer/user/reset/1/1479116374/yAhJ8jtCNB4TCc7f6hkWCkEbi9N0-HQY_VSk0RP-KSg/login

When i visited the above link i got 
Not Found

The requested URL /user/reset/1/1479116374/yAhJ8jtCNB4TCc7f6hkWCkEbi9N0-HQY_VSk0RP-KSg/login was not found on this server.

Apache/2.4.18 (Ubuntu) Server at local.computer Port 80

**Comment by helmo** [comment]
Inside the container Aegir cannot see that you tied it to port 81 outside the container... Thus you have to add the :81 to your link .. e.g. http://local.computer:81/user....

A workaround for this is to have the apache that does listen on port 80 proxy the requests for local.computer to port 81.

You could have a vhost like ....
```
<VirtualHost *:80>
    ServerName local.computer
    ServerAdmin webmaster@initfour.nl

    ServerAlias s1.local.computer s2.local.computer s3.local.computer

    ProxyRequests Off
    ProxyPreserveHost On
    ProxyPass / http://127.0.0.1:81/ max=100
    ProxyPassReverse / http://127.0.0.1:81/
    <Proxy>
        Allow from all
    </Proxy>

</VirtualHost>
```

Note that you need to have the proxy_http apache module enabled.

**Comment by Yusadolat** [comment]
@helmo please help look into this..

**Comment by Yusadolat** [comment]
@helmo After adding 81 to the link it works but am not able to login as it doesn't let me reset password.Please what is the default username and password to login?

**Comment by helmo** [comment]
There is none .... you can use `drush @hostmaster uli` to get a new link.
