### ISSUE TITLE
COMPOSE_HTTP_TIMEOUT may be ignored

### ISSUE THREAD

**Issue by dmtucker** [aegir-project/dockerfiles#25]
If you are in a situation similar to mine (likely considering my problem led me to this project), the Travis env for your project may be ignoring your global `COMPOSE_HTTP_TIMEOUT` when using `sudo`! My solution has been to use `sudo -E` (not necessarily successfully, still testing); however, I am using an instance of Travis CI Enterprise that does not yet support Docker as a service. So, you may want to look into it :+1:

**Comment by helmo** [comment]
Thanks for letting us know.
