### ISSUE TITLE
Some errors during hostmaster install

### ISSUE THREAD

**Issue by mstenta** [aegir-project/dockerfiles#26]
I'm seeing a few errors during the installation of hostmaster.

<code>
hostmaster_1  | Unable to load Array driver for the dns service: Expecting class         [error]
hostmaster_1  | Provision_Service_dns_Array
hostmaster_1  | Unable to load Array driver for the dns service: Expecting class         [error]
hostmaster_1  | Provision_Service_dns_Array
</code>

It doesn't seem to cause the installation to fail, and Aegir does work afterwards. So not critical... just something to document and maybe fix...

**Comment by jonpugh** [comment]
Hmm I think this is from some cutting edge provision issue... Could you submit to Drupal.org/project/provision?

**Comment by mstenta** [comment]
Posted: https://www.drupal.org/node/2835818

Closing this issue. If it turns out to be a Docker+Aegir issue, we can reopen, but you're probably right that it is Provision.
