### ISSUE TITLE
Warning, things you need to know with external mysql database.

### ISSUE THREAD

**Issue by apassi** [aegir-project/dockerfiles#32]
I need to warn to use aegir in docker with external mysql database.
The aegir creates ip based grant for each site to the mysql access table.

In docker, the ip is not generally defined as a static, an can change anytime. I made some reseach to change the aegir code to use hostname instead ip ( so we could use docker alias ), but it seems that mysql does reverse dns for the connecting hostname, so using the hostnames just dont work.

Only way to use external mysql is to use static ip's for the aegir docker container, or change the aegir code to do the wildcard / network masked user grants.

**Comment by helmo** [comment]
Some related changes were recently committed via https://www.drupal.org/node/2794915 and added here in d45e11ff39ac9ba96c1e0427099b35f488966972
