### ISSUE TITLE
Use provision from pull request branch

### ISSUE THREAD

**Issue by helmo** [aegir-project/dockerfiles#4]
docker-entrypoint.sh used `drush dl` to download drush, but I don't think that supports feature branches.

We'd need this for https://github.com/aegir-project/provision/pull/2

**Comment by jonpugh** [comment]
It only runs if provision is not found.

For the tests, provision is mounted in place before the entrypoint script runs, so the submitted code is what gets tested.

I have to do one last round of testing to ensure pull requests from forked repos test properly, but this is already resolved.
