### ISSUE TITLE
hub.docker.com account

### ISSUE THREAD

**Issue by helmo** [aegir-project/dockerfiles#5]
@jonpugh 
can you add the project account for https://hub.docker.com/r/aegir/hostmaster/ to the project's lastpass?

**Comment by jonpugh** [comment]
The accounts are personal like on github.

Please signup and tell me your username and I will add you and whoever else
to the aegir organization.

**Comment by helmo** [comment]
Ah, ok... It's https://hub.docker.com/u/helmo42/

**Comment by jonpugh** [comment]
Ok, I've added you to the owners of the aegir organization, it should give you full access.

Can you confirm, @helmo ?

**Comment by ergonlogic** [comment]
Please also add me: "ergonlogic"

**Comment by jonpugh** [comment]
@ergonlogic: done!

**Comment by helmo** [comment]
Seems to work, thanks.
